export const menuItems = [
  {
    name: "Dashboard",
    exact: true,
    to: "/dashboard",
    iconClassName: "bi bi-cast",
    route_key: "dashboard",
    privilege: ["SUPER_ADMIN"],
  },
  {
    name: "Tickets",
    exact: true,
    to: "/tickets",
    iconClassName: "bi bi-layout-text-sidebar-reverse",
    route_key: "tickets",
    privilege: ["SUPER_ADMIN"],
    subMenus: [
      {
        name: "Search Ticket",
        exact: true,
        to: "/tickets/gemstone-origins",
        route_key: "gemstone-origins",
        privilege: ["SUPER_ADMIN"],
      },
      {
        name: "Generate Reports",
        exact: true,
        to: "/tickets/gemstone-types",
        route_key: "gemstone-types",
        privilege: ["SUPER_ADMIN"],
      },
    ],
  },
  {
    name: "Issue Type Operations",
    exact: true,
    to: "/issue-type",
    iconClassName: "bi bi-sliders",
    route_key: "issue-type",
    privilege: ["SUPER_ADMIN"],
    subMenus: [
      {
        name: "Create New Issue Type",
        exact: true,
        to: "/issue-type/create-new",
        route_key: "create-issue-type",
        privilege: ["SUPER_ADMIN"], 
      },
      {
        name: "Search Issue Types",
        exact: true,
        to: "/issue-type/search",
        route_key: "search-issue-type",
        privilege: ["SUPER_ADMIN"],
      },
      {
        name: "View Existing Issue Types",
        exact: true,
        to: "/issue-type/view",
        route_key: "view-issue-type",
        privilege: ["SUPER_ADMIN"],
      },
      {
        name: "Update Issue Type",
        exact: true,
        to: "/issue-type/update",
        route_key: "update-issue-type",
        privilege: ["SUPER_ADMIN"],
      },
      {
        name: "Delete Issue Type",
        exact: true,
        to: "/issue-category/delete",
        route_key: "delete-issue-type",
        privilege: ["SUPER_ADMIN"],
      },
    ],
  },
  {
    name: "Issue Category Operations",
    exact: true,
    to: "/issue-category",
    iconClassName: "bi bi-tags",
    route_key: "categories",
    privilege: ["SUPER_ADMIN"],
    subMenus: [
      {
        name: "Create New Issue Category",
        exact: true,
        to: "/issue-category/create-new",
        route_key: "create-issue-category",
        privilege: ["SUPER_ADMIN"], 
      },
      {
        name: "Search Issue Categories",
        exact: true,
        to: "/issue-category/search",
        route_key: "search-issue-category",
        privilege: ["SUPER_ADMIN"],
      },
      {
        name: "View Existing Issue Categories",
        exact: true,
        to: "/issue-category/view",
        route_key: "view-issue-category",
        privilege: ["SUPER_ADMIN"],
      },
      {
        name: "Update Issue Category",
        exact: true,
        to: "/issue-category/update",
        route_key: "update-issue-category",
        privilege: ["SUPER_ADMIN"],
      },
      {
        name: "Delete Issue Category",
        exact: true,
        to: "/issue-category/delete",
        route_key: "delete-issue-category",
        privilege: ["SUPER_ADMIN"],
      },
    ],
  },
  {
    name: "Users",
    exact: true,
    to: "/user",
    iconClassName: "bi bi-people",
    route_key: "user-role",
    privilege: ["SUPER_ADMIN"],
    subMenus: [
      {
        name: "Add User",
        exact: true,
        to: "/user/add-user",
        route_key: "add-user",
        privilege: ["SUPER_ADMIN"], 
      },
      {
        name: "Add User Role",
        exact: true,
        to: "/user/add-user-role",
        route_key: "add-user-role",
        privilege: ["SUPER_ADMIN"], 
      },
      {
        name: "Add Function",
        exact: true,
        to: "/user/add-function",
        route_key: "add-function",
        privilege: ["SUPER_ADMIN"],
      },
      {
        name: "Assign Function",
        exact: true,
        to: "/user/assign-function",
        route_key: "assign-function",
        privilege: ["SUPER_ADMIN"],
      },
    ],
  },
  {
    name: "Settings",
    exact: true,
    to: "/settings",
    iconClassName: "bi bi-gear",
    route_key: "settings",
    privilege: ["SUPER_ADMIN"],
  },
];
