export const BE_API_URL = "http://localhost:8080";
export const FE_API_URL = "http://localhost:3000";
export const IMAGE_PATH = process.env.REACT_APP_IMAGEKIT_URL;

export const BASE_API_URL = `${BE_API_URL}`;
export const BASE_FE_URL = `${FE_API_URL}`;

export const apis = {
  ACCEPT_TICKET: `${BASE_API_URL}/acceptTicket`,
  ACTIVE_TICKET_COUNT: `${BASE_API_URL}/getActiveTicketCount`,
  ADD_COMMENT: `${BASE_API_URL}/addComment`,
  ADD_FUNCTION: `${BASE_API_URL}/addFunction`,
  ADD_ISSUES_CATEGORY: `${BASE_API_URL}/addIssueCategory`,
  ADD_TICKET: `${BASE_API_URL}/addTicket`,
  ADD_USER: `${BASE_API_URL}/addUser`,
  ADD_USER_ROLE: `${BASE_API_URL}/addUserRole`,
  ASSIGN_FUNCTION: `${BASE_API_URL}/assignFunction`,
  ASSIGN_TICKET: `${BASE_API_URL}/assignTicket`,
  ASSIGN_USER_ROLES: `${BASE_API_URL}/assignUserRoles`,
  ASSIGNED_TICKET_COUNT: `${BASE_API_URL}/getAssignedTicketCount`,
  AUTHENTICATE_USER: `${BASE_API_URL}/authenticateUser`,
  CHANGE_PASSWORD: `${BASE_API_URL}/changePassword`,
  CHECK_INITIAL_LOGIN_STATUS: `${BASE_API_URL}/checkInitialLoginStatus`,
  CLOSE_TICKET: `${BASE_API_URL}/closeTicket`,
  CLOSED_TICKET_COUNT: `${BASE_API_URL}/getClosedTicketCount`,
  COMPLETED_TICKET_COUNT: `${BASE_API_URL}/getCompletedTicketCount`,
  DELETE_ISSUE_CATEGORY: `${BASE_API_URL}/deleteIssueCategory`,
  DELETE_TICKET: `${BASE_API_URL}/deleteTicket`,
  DELETE_USER: `${BASE_API_URL}/deleteUser`,
  DELETE_USER_ROLE: `${BASE_API_URL}/deleteUserRole`,
  EXPORT_TICKETS: `${BASE_API_URL}/exportTickets`,
  FUNCTION_DATA: `${BASE_API_URL}/deleteFunction`,
  FUNCTION_PRIVILEGES: `${BASE_API_URL}/getFunctionPrivileges`,
  GET_ALL_ISSUE_CATEGORIES: `${BASE_API_URL}/getAllIssueCategories`,
  GET_ALL_USER_DETAILS: `${BASE_API_URL}/getAllUserDetails`,
  GET_ALL_USER_FUNCTIONS: `${BASE_API_URL}/getAllUserFunctions`,
  GET_ALL_USER_ROLES: `${BASE_API_URL}/getAllUserRoles`,
  GET_BRANCH_DIVISION_BY_LOCATION: `${BASE_API_URL}/getBranchDivisionByLocation`,
  GET_COMMENT_BY_TICKET_ID: `${BASE_API_URL}/getCommentsByTicketId`,
  GET_DISPLAY_NAME_BY_USERNAME: `${BASE_API_URL}/getDisplayNameByUsername`,
  GET_EMERGENCY_LEVELS: `${BASE_API_URL}/getEmergencyLevels`,
  GET_FUNCTIONS: `${BASE_API_URL}/getFunctions`,
  GET_FUNCTION_DETAILS_BY_ID: `${BASE_API_URL}/getFunctionDetailsByFunctionId`,
  GET_IP_ADDRESS: `${BASE_API_URL}/getIPAddress`,
  GET_ISSUE_CATEGORIES: `${BASE_API_URL}/getAllIssueCategories`,
  GET_ISSUE_CATEGORIES_BY_ISSUE_TYPE: `${BASE_API_URL}/getIssueCategoriesByIssueType`,
  GET_ISSUE_CATEGORY_DETAILS_BY_ID: `${BASE_API_URL}/getIssueCategoryDetailsById`,
  GET_ISSUE_TYPES: `${BASE_API_URL}/getIssueTypes`,
  GET_LOCATIONS: `${BASE_API_URL}/getLocations`,
  GET_STATUSES: `${BASE_API_URL}/getStatuses`,
  GET_TICKET: `${BASE_API_URL}/getTicket`,
  GET_TICKET_BY_ID: `${BASE_API_URL}/getTicketByID`,
  GET_USER_DETAILS_BY_USERNAME: `${BASE_API_URL}/getUserDetailsByUsername`,
  GET_USER_DETAILS_BY_USER_ROLE: `${BASE_API_URL}/getUserDetailsByUserRole`,
  GET_USER_DETAILS_FOR_TICKET_BY_USERNAME: `${BASE_API_URL}/getUserDetailsForTicketByUsername`,
  GET_USER_LIST_BY_USER_ROLE: `${BASE_API_URL}/getUserListsByUserRole`,
  GET_USER_ROLES: `${BASE_API_URL}/getUserRoles`,
  GET_USER_ROLE_FUNCTIONS: `${BASE_API_URL}/getUserRoleFunctions`,
  GET_USER_ROLES_FOR_USERNAME: `${BASE_API_URL}/getUserRolesForUsername`,
  IMAGES: `${BASE_API_URL}/images`,
  NEW_TICKET_COUNT: `${BASE_API_URL}/getNewTicketCount`,
  PAGE_PRIVILEGES: `${BASE_API_URL}/getPagePrivileges`,
  REJECT_TICKET: `${BASE_API_URL}/rejectTicket`,
  SAVE_PERCENTAGE: `${BASE_API_URL}/savePercentage`,
  SAVE_STATUS: `${BASE_API_URL}/saveStatus`,
  SEARCH_TICKETS: `${BASE_API_URL}/searchTickets`,
  TOTAL_TICKET_COUNT: `${BASE_API_URL}/getTotalTicketCount`,
  UPDATE_FUNCTION: `${BASE_API_URL}/updateFunction`,
  UPDATE_ISSUE_CATEGORY: `${BASE_API_URL}/updateIssueCategory`,
  UPDATE_TICKET: `${BASE_API_URL}/updateTicket`,
  UPDATE_USER: `${BASE_API_URL}/updateUser`,
  UPDATE_USER_ROLE: `${BASE_API_URL}/updateUserRole`,


  //Front-end URLs

  TICKETS: `${BASE_FE_URL}/tickets`,
  FUNCTION: `${BASE_FE_URL}/user/function`,
  DASHBOARD: `${BASE_FE_URL}/dashboard`,
  ISSUE_CATEGORY: `${BASE_FE_URL}/issue-category`,
  USER: `${BASE_FE_URL}/user`,
  USER_ROLE: `${BASE_FE_URL}/user/user-role`,
};

export const ckeditorConfig = {
  toolbar: [
    "heading",
    "|",
    "fontColor",
    "fontBackgroundColor",
    "|",
    "bold",
    "italic",
    "link",
    "bulletedList",
    "numberedList",
    "blockQuote",
    "|",
    "insertTable",
    "mediaEmbed",
    "|",
    "undo",
    "redo",
    "|",
    "imageUpload",
    "imageStyle:full",
    "imageStyle:side",
    "|",
    "code",
    "CodeBlock",
    "|",
  ],
};